# Generated by Django 3.1.3 on 2022-02-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20220204_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='writer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
