# Generated by Django 3.1.3 on 2022-03-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_notice_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
    ]
